#!/usr/bin/env node
// Load this copy of opencode-token-norm as a LOCAL OpenCode plugin.
//
// Why this exists: OpenCode >= 1.17 fails to load npm-spec plugins listed in
// the `plugin` config array on some builds/environments, and the failure is
// silent (no log, no error; upstream: silent plugin-load failures). A local
// plugin file with the same code loads fine, so this writes a one-line wrapper
// into the global plugins directory that re-exports this checkout's build.
//
// The wrapper points at dist/index.js, so `npm run build` is required first and
// later rebuilds take effect on the next OpenCode restart. If the checkout moves
// or is deleted, re-run this script from the new location.
import { existsSync, mkdirSync, rmSync, writeFileSync, readFileSync } from "node:fs"
import { homedir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"

const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const entry = join(repo, "dist", "index.js")
const configHome = process.env.XDG_CONFIG_HOME || join(homedir(), ".config")
const pluginsDir = join(configHome, "opencode", "plugins")
const target = join(pluginsDir, "opencode-token-norm.js")

if (process.argv.includes("--remove")) {
  if (existsSync(target)) {
    rmSync(target)
    console.log(`removed ${target}`)
  } else {
    console.log(`nothing to remove at ${target}`)
  }
  process.exit(0)
}

if (!existsSync(entry)) {
  console.error(`no build found at ${entry}\nrun \`npm run build\` first, then re-run this script`)
  process.exit(1)
}

const contents = [
  "// Generated by scripts/install-local.mjs. Re-run that script after moving this checkout.",
  `export * from ${JSON.stringify(pathToFileURL(entry).href)}`,
  "",
].join("\n")

mkdirSync(pluginsDir, { recursive: true })
if (existsSync(target) && readFileSync(target, "utf8") === contents) {
  console.log(`already up to date: ${target}`)
} else {
  writeFileSync(target, contents, "utf8")
  console.log(`wrote ${target}`)
}

console.log(
  [
    "",
    "Next: restart OpenCode, then verify with docs/smoke-test.md step 1.",
    "If ~/.config/opencode/opencode.json still lists \"opencode-token-norm\" in the",
    "`plugin` array, remove it — otherwise a future OpenCode that loads npm specs",
    "again will run this plugin twice.",
  ].join("\n"),
)
